apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  APP_ID: "Shipit-Clicker-{{ .Release.Name }}"
  OPENAPI_SPEC: "/api/v1/spec"
  OPENAPI_ENABLE_RESPONSE_VALIDATION: "false"
  PORT: "3000"
  METRICS_PORT: "9090"
  LOG_LEVEL: "info"
  REQUEST_LIMIT: "100kb"
  REDIS_HOST: "localhost"
  REDIS_REPLICA: "localhost"
  REDIS_PORT: "6379"
  JAEGER_AGENT_HOST: "localhost"
  JAEGER_AGENT_PORT: "6831"
  JAEGER_SAMPLING_ENDPOINT: "http://localhost:5778/sampling"
  JAEGER_COLLECTOR_ENDPOINT: "http://jaeger-collector.observability.svc:14268/api/traces"
