apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-envoy-sidecar-configmap
data:
  envoy-config: |
    admin:
      access_log_path: {{ .Values.envoy.accessLog }}
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: 9901
    static_resources:
      listeners:
        - name: shipitclicker_listener
          address:
            socket_address:
              address: "0.0.0.0"
              port_value: 4000
          filter_chains:
            - filters:
              - name: "envoy.http_connection_manager"
                typed_config: 
                  "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                  codec_type: auto
                  stat_prefix: ingress_http
                  route_config:
                    name: shipitclicker_route
                    virtual_hosts:
                    - name: backend
                      domains:
                      - "*"
                      routes:
                      - match:
                          prefix: "/"
                        route:
                          cluster: shipitclicker_cluster
                  http_filters:
                  - name: envoy.filters.http.router
                    typed_config: {}
        - name: redis_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 6379
          filter_chains:
            - filters:
              - name: envoy.filters.network.redis_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                  stat_prefix: egress_redis
                  cluster: redis_cluster
        - name: "envoy-prometheus-http-listener"
          address:
            socket_address:
              address: "0.0.0.0"
              port_value: 9902
          filter_chains:
            - filters:
              - name: "envoy.http_connection_manager"
                typed_config:
                  "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                  codec_type: auto
                  stat_prefix: ingress_metrics
                  route_config:
                    name: local_route
                    virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                      - match:
                          prefix: "/metrics"
                        route:
                          cluster: envoy_admin
                          prefix_rewrite: "/stats/prometheus"
                  http_filters:
                  - name: envoy.filters.http.router
                    typed_config: {}
      clusters:
      - name: shipitclicker_cluster
        connect_timeout: 0.25s
        type: static
        load_assignment:
          cluster_name: shipitclicker
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: "127.0.0.1"
                    port_value: 3000
        circuit_breakers:
          thresholds:
            - priority: DEFAULT
              max_connections: {{ .Values.envoy.maxRequests }}
              max_pending_requests: {{ .Values.envoy.maxRequests }}
              max_requests: {{ .Values.envoy.maxRequests }}
              max_retries: {{ .Values.envoy.maxRetries }}
      - name: redis_cluster
        connect_timeout: 1s
        type: strict_dns
        lb_policy: MAGLEV
        load_assignment:
          cluster_name: redis_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: redis-master
                    port_value: 6379
      - name: envoy_admin
        connect_timeout: 0.25s
        type: static
        load_assignment:
          cluster_name: envoy_admin
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: "127.0.0.1"
                    port_value: 9901

