LABEL "version"="1.1.2-test"

LABEL "description"="Kontener środowiska programistycznego do testowania najnowszej poprawki zabezpieczeń. Jeszcze nie przeznaczony do wersji produkcyjnej."

LABEL "security.txt"="https://respository.example.com/my_project/security.txt"
 
